export const SET_SECTION = 'SET_SECTION';
export const FETCH_PORTFOLIO_SUCCESS = 'FETCH_PORTFOLIO_SUCCESS';
export const FETCH_PORTFOLIO_REQUEST = 'FETCH_PORTFOLIO_REQUEST';
export const FETCH_PORTFOLIO_FAILURE = 'FETCH_PORTFOLIO_FAILURE';
export const ADD_PORTFOLIO_ITEM = 'ADD_PORTFOLIO_ITEM';
export const REMOVE_PORTFOLIO_ITEM = 'REMOVE_PORTFOLIO_ITEM';
