export const SET_SECTION = 'SET_SECTION';

export const GET_PORTFOLIO_ITEMS = 'GET_PORTFOLIO_ITEMS';
export const GET_PORTFOLIO_ITEMS_SUCCESS = 'GET_PORTFOLIO_ITEMS_SUCCESS';
export const GET_PORTFOLIO_ITEMS_ERROR = 'GET_PORTFOLIO_ITEMS_ERROR';

export const GET_ADMIN_ITEMS = 'GET_ADMIN_ITEMS';
export const GET_ADMIN_ITEMS_SUCCESS = 'GET_ADMIN_ITEMS_SUCCESS';
export const GET_ADMIN_ITEMS_ERROR = 'GET_ADMIN_ITEMS_ERROR';
export const MERGE_ADMIN_ITEM = 'MERGE_ADMIN_ITEM';
export const REMOVE_ADMIN_ITEM = 'REMOVE_ADMIN_ITEM';

export const POST_AUTH = 'POST_AUTH';
export const POST_AUTH_SUCCESS = 'POST_AUTH_SUCCESS';
export const POST_AUTH_ERROR = 'POST_AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

