export const SET_SECTION = 'SET_SECTION';

export const FETCH_PORTFOLIO_REQUEST = 'FETCH_PORTFOLIO_REQUEST';
export const FETCH_PORTFOLIO_SUCCESS = 'FETCH_PORTFOLIO_SUCCESS';
export const FETCH_PORTFOLIO_FAILURE = 'FETCH_PORTFOLIO_FAILURE';
export const ADD_PORTFOLIO_ITEM = 'ADD_PORTFOLIO_ITEM';
export const REMOVE_PORTFOLIO_ITEM = 'REMOVE_PORTFOLIO_ITEM';

export const POST_AUTH = 'POST_AUTH';
export const POST_AUTH_SUCCESS = 'POST_AUTH_SUCCESS';
export const POST_AUTH_ERROR = 'POST_AUTH_ERROR';

export const POST_MESSAGE = 'POST_MESSAGE';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';
