export const ADD_PORTFOLIO_ITEM = 'ADD_PORTFOLIO_ITEM';
export const REMOVE_PORTFOLIO_ITEM = 'REMOVE_PORTFOLIO_ITEM';
export const FETCH_PORTFOLIO_TYPE = 'FETCH_PORTFOLIO_TYPE';
export const SET_PORTFOLIO_TYPE = 'SET_PORTFOLIO_TYPE';
export const ADD_PORTFOLIO_TYPE = 'ADD_PORTFOLIO_TYPE';
