const domain = 'https://farrung.com';
const api = `${domain}/api/`;
export const getPortfolioUrl = `${api}allportfolio/`;
export const postAuthUrl = `${api}authrequest/`;
export const postMessageUrl = `${api}contact/`;
export const addPortfolioItemUrl = `${api}addPortfolioItem/`;
export const editPortfolioItemUrl = `${api}editPortfolioItem/`;
export const removePortfolioItemUrl = `${api}removePortfolioItem/`;
export const imgPath = `${domain}/images/`;
